nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-berry.cjs
cacheFolder: ./.yarn/offline-cache
supportedArchitectures:
  cpu:
    - current
    - x86
    - x64
    - ia32
    - arm
    - arm64
  os:
    - current
    - darwin
    - linux
    - win32
