name: Black Duck Pro
on:
  pull_request:
    branches:
      - master
  schedule:
    # Every Monday at 08:00
    - cron: "0 08 * * 1"
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Run Synopsys Detect
        uses: synopsys-sig/detect-action@v0.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 7.9.0
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
